### ISSUE TITLE
ROLDAN URIEL ARCADIO AVILA LINEA DEL TIEMPO 

### ISSUE THREAD

**Issue by Roldanuriel** [SistemasTecTlaxiaco/actividad-7-Roldanuriel#1]

**Comment by Roldanuriel** [comment]
![Roldán Uriel Arcadio Avila 1BS linea de tiempo](https://user-images.githubusercontent.com/112295222/197447554-4ff57e53-0cd5-45fd-afa7-dfd6ce7edf19.png)

**Comment by Jaczibeth** [comment]
del 20% obtuviste un 19%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
